#!/usr/bin/perl -w
use warnings;
use strict;
use Text::Iconv;

#$converter = Text::Iconv->new("fromcode", "tocode");
#$converted = $converter->convert("Text to convert");

die "Usage: mm src [dest]\n\n"
	if (1 > @ARGV);

my $src = shift @ARGV;
my $dest = shift @ARGV || "minmax.csv";

print "src: $src\ndest: $dest\n";



my $min = 0.0; # minimal price for this one hystory
my $max = 0.0; # maxmum price for this one hystory
my $nd_cnt = 50; # number of diapasones [!] should by ajustable!
my $dia = 0.0; # size of the diapason
my $delta = 0.0; # delta between minimum and maximum prices shows the work area

open my $fin, "<$src"
	or die "Can't open $src file: $!";

grep { chomp; #print "$_\n";
	#my $converter = Text::Iconv->new("CP1251", "UTF-8");
	my $converted = $_;#$converter->convert($_);
	if ( $converted =~ m/(\d+.\d+)/gi ) {
		#print "[$converted]\n";
		$min = $1
			unless $min;
		$max = $1
			unless $max;
		$min = $1
			if ($min > $_);
		$max = $1
			if ($max < $_);
	}
} <$fin>;
close $fin 
	or warn "Can't close $src file: $!";

$delta = $max - $min;
$dia = $delta / $nd_cnt;

open my $fout, ">$dest"
	or die "Can't open $dest file: $!";

print $fout "min:$min\n";
print $fout "max:$max\n";
print $fout "delta:$delta\n";
print $fout "dia:$dia\n";
print $fout "dias:$nd_cnt\n";

close $fout 
	or warn "Can't close $dest file: $!";
